/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Movies: () => import('#controllers/movies_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Rooms: () => import('#controllers/rooms_controller'),
  Screenings: () => import('#controllers/screenings_controller'),
  Stats: () => import('#controllers/stats_controller'),
  Tickets: () => import('#controllers/tickets_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Users: () => import('#controllers/users_controller'),
}
