/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Movies: () => import('#controllers/movies_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Rooms: () => import('#controllers/rooms_controller'),
  Screenings: () => import('#controllers/screenings_controller'),
  Statss: () => import('#controllers/statss_controller'),
  Tickets: () => import('#controllers/tickets_controller'),
  Users: () => import('#controllers/users_controller'),
}
