services:
  db:
    image: postgres:16-alpine
    container_name: le_cinema_db
    environment:
      POSTGRES_USER: ${DB_USER:-adonis}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE:-le_cinema}
    ports:
      - '5432:5432'
